name: "test"
on:
  issues:
    types:
      - assigned
      - labeled
      - unassigned
      - unlabeled

jobs:
  # make sure the action works on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
